language: php
sudo: false
php:
  - 5.5
script: phpunit --configuration .phpunit.xml
notifications:
  email: false
  irc:
    skip_join: true
    on_success: never
    on_failure: always
    channels:
      - "chat.freenode.net#steamlug"
    template:
      - "%{repository}#%{build_number} (%{commit} by %{author}): %{message}"
      - "Build details: %{build_url}"
install:
    - composer require seld/jsonlint:1.3.1
